version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    ports:
      - "4000:4000" # Host Port: Container Port
    depends_on:
      - mongo
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm start

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
